name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew buildPlugin

    # Not yet setup
    #  - name: Publish plugin release
    #    env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    run: |
    #      ./gradlew publishPlugin -PpublishToken=${{ secrets.PUBLISH_TOKEN }}

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distributions/plandex-plugin-1.0-SNAPSHOT.zip
          asset_name: plandex-intellij-${{ github.ref }}.zip
          asset_content_type: application/zip
